import { contrastRatio } from "@dylanmerigaud/microsaas-kit/contrast";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { test } from "node:test";

/**
 * The accessibility floor of this site's palette, measured on the tokens actually written into
 * app/globals.css. Spec: docs/DESIGN-FINTECH-2026-08-24.md in the growth-cockpit repo, the WCAG
 * 2.2 AA plus RGAA section. Body AND secondary text at 4.5:1 (1.4.3, RGAA 3.2), the focus
 * indicator at 3:1 (1.4.11, RGAA 10.7).
 *
 * Adapted from lib/design-contrast.test.ts in microsaas-template, which measures the same floor
 * against an oklch preset generated by `pnpm run setup theme`. This site has neither: its palette
 * is nine hand-picked hex values with no theme step and no preset list, so the whole thing is read
 * straight out of the CSS and the oklch machinery is not needed. What carries over unchanged is
 * the principle: the file that SHIPS is the file that is measured, so a hand edit to a colour is
 * caught here and not on the deployed page.
 *
 * TWO GROUNDS, NOT TWO THEMES. There is no dark mode and no `.dark` class. The page is a paper
 * sheet (--color-paper) with bands of near-black cut into it (--color-ink-deep, marked `.on-dark`
 * in the markup), and each ground carries its own ink, its own secondary grey and its own green.
 * Both ship on every page, so both are held to the same floor: neither is a fallback the reader
 * can avoid.
 *
 * THE ALPHA PAIRS ARE THE POINT. The pairs most likely to fail are not the raw tokens, they are
 * the `text-ink/70`, `text-ink/75` and `text-paper/85` utilities carrying the running body copy: a
 * translucent grey on a light ground is the single most common way a finance page lands under
 * 4.5:1. Those are composited here the way the browser composites them and measured as the colour
 * a reader actually sees, not as the token they are written from.
 */

const css = readFileSync(join("app", "globals.css"), "utf8");

/**
 * Every rule body for one selector, in file order, concatenated. A mode's tokens are spread over
 * more than one block, and the LAST declaration of a name wins, which is what the cascade does at
 * equal specificity.
 *
 * Reading by SELECTOR rather than sweeping the whole file is load bearing, and the first draft of
 * this test got it wrong: --ring is declared twice, once on `:root` as the stamp green and once on
 * `.on-dark` as the brighter green for the dark bands. A flat sweep took the last one and then
 * measured the dark-band ring against the paper, reporting 2.06:1 for a pair that never occurs.
 * A token that exists in two scopes has to be read in the scope it applies to.
 */
const rulesFor = (selector: string): string => {
  const bodies: string[] = [];
  let cursor = 0;
  for (;;) {
    const start = css.indexOf(`${selector} {`, cursor);
    if (start === -1) break;
    const open = css.indexOf("{", start);
    const close = css.indexOf("}", open);
    assert.notEqual(close, -1, `unterminated "${selector}" rule in app/globals.css`);
    bodies.push(css.slice(open + 1, close));
    cursor = close;
  }
  assert.ok(bodies.length > 0, `no "${selector}" rule in app/globals.css`);
  return bodies.join("\n");
};

/** Every `--name: value;` declaration of one block, last one winning. */
const parseVars = (block: string): Record<string, string> => {
  const vars: Record<string, string> = {};
  for (const match of block.matchAll(/--([\w-]+):\s*([^;]+);/g)) {
    const [, name, value] = match;
    if (name !== undefined && value !== undefined) vars[name] = value.trim();
  }
  return vars;
};

/** The nine palette colours; `@theme` is where this site declares them, not `:root`. */
const PALETTE = parseVars(rulesFor("@theme"));
/** The paper sheet: palette plus the structural tokens `:root` adds. */
const PAPER = { ...PALETTE, ...parseVars(rulesFor(":root")) };
/** The dark bands: the same, with `.on-dark`'s overrides applied on top. */
const INK = { ...PAPER, ...parseVars(rulesFor(".on-dark")) };

type Scope = Readonly<Record<string, string>>;

/**
 * Resolve a token to a literal `#rrggbb` within one scope, following `var()` aliases. --ring is
 * deliberately an alias of --color-stamp rather than a copy of its hex, so this has to walk the
 * chain: a test that only read literals would silently stop measuring the focus ring the day it
 * was pointed somewhere new.
 */
const hexOf = (scope: Scope, name: string, seen: readonly string[] = []): string => {
  // A literal passes straight through: Tailwind's own `text-white` is not a token of this site,
  // and declaring one just so a test could name it would put a colour in the palette that no rule
  // reads.
  if (name.startsWith("#")) return name.toLowerCase();
  assert.ok(!seen.includes(name), `--${name} resolves in a cycle: ${[...seen, name].join(" -> ")}`);
  const raw = scope[name];
  assert.ok(raw !== undefined, `token absent from app/globals.css: --${name}`);
  const alias = /^var\(\s*--([\w-]+)\s*\)$/.exec(raw);
  if (alias?.[1] !== undefined) return hexOf(scope, alias[1], [...seen, name]);
  assert.match(raw, /^#[\da-f]{6}$/i, `--${name} is not a #rrggbb colour: "${raw}"`);
  return raw.toLowerCase();
};

/** The three 0..255 channels of a `#rrggbb` colour. */
const channelsOf = (hex: string): number[] =>
  [1, 3, 5].map((at) => Number.parseInt(hex.slice(at, at + 2), 16));

/**
 * The colour the browser paints for `text-ink/70` and friends: the source-over composite of a
 * translucent foreground on an OPAQUE ground. Only correct because every ground below is opaque,
 * which on this site they are (--color-paper and --color-ink-deep both paint the full sheet).
 */
const composite = (foreground: string, ground: string, alpha: number): string => {
  const mixed = channelsOf(foreground).map((channel, index) => {
    const under = channelsOf(ground)[index];
    assert.ok(under !== undefined, "colours must have three channels");
    return Math.round(channel * alpha + under * (1 - alpha));
  });
  return `#${mixed.map((channel) => channel.toString(16).padStart(2, "0")).join("")}`;
};

const atLeast = (measured: number, floor: number, label: string): void => {
  assert.ok(
    measured >= floor,
    `${label}: measured ${measured.toFixed(2)}:1, floor is ${floor.toFixed(1)}:1`
  );
};

/** One measured pair. `alpha` is the opacity utility the markup applies to the foreground. */
type Pair = {
  readonly label: string;
  readonly foreground: string;
  readonly ground: string;
  readonly floor: number;
  readonly alpha?: number;
};

const measure = (scope: Scope, { label, foreground, ground, floor, alpha }: Pair): void => {
  const groundHex = hexOf(scope, ground);
  const inkHex =
    alpha === undefined
      ? hexOf(scope, foreground)
      : composite(hexOf(scope, foreground), groundHex, alpha);
  atLeast(contrastRatio(inkHex, groundHex), floor, label);
};

// The paper sheet: the home page below the hero, and the whole of /blog, /privacy and /work/*.
const ON_PAPER: readonly Pair[] = [
  { label: "body text (ink on paper)", foreground: "color-ink", ground: "color-paper", floor: 4.5 },
  {
    label: "text on a figure card (ink on paper-dim)",
    foreground: "color-ink",
    ground: "color-paper-dim",
    floor: 4.5,
  },
  {
    label: "secondary text (trace on paper)",
    foreground: "color-trace",
    ground: "color-paper",
    floor: 4.5,
  },
  {
    label: "secondary text on a card (trace on paper-dim)",
    foreground: "color-trace",
    ground: "color-paper-dim",
    floor: 4.5,
  },
  {
    // --ring resolves through to this on the paper ground, so one measurement covers both the
    // prose links in the notes and the focus indicator the a11y floor draws.
    label: "prose link and focus ring (ring on paper)",
    foreground: "ring",
    ground: "color-paper",
    floor: 4.5,
  },
  {
    label: "primary CTA label (paper on ink)",
    foreground: "color-paper",
    ground: "color-ink",
    floor: 4.5,
  },
  {
    // app/work/[slug]/page.tsx puts white on the stamp green for its live-project button: the one
    // place a colour carries text rather than sitting beside it.
    label: "green CTA label (white on stamp)",
    foreground: "#ffffff",
    ground: "color-stamp",
    floor: 4.5,
  },
  {
    // The underline under the refused word in the pull statement. Non-text contrast, 1.4.11.
    label: "pull-statement underline (flag on paper)",
    foreground: "color-flag",
    ground: "color-paper",
    floor: 3,
  },
  {
    label: "hero and contact body copy (ink at 70 percent on paper)",
    foreground: "color-ink",
    ground: "color-paper",
    floor: 4.5,
    alpha: 0.7,
  },
  {
    label: "article lead and engagement rows (ink at 75 percent on paper)",
    foreground: "color-ink",
    ground: "color-paper",
    floor: 4.5,
    alpha: 0.75,
  },
  {
    label: "consent banner text (ink at 80 percent on paper)",
    foreground: "color-ink",
    ground: "color-paper",
    floor: 4.5,
    alpha: 0.8,
  },
];

// The dark bands: the hero, the experience ledger, /404 and the error page. Marked `.on-dark`,
// where --ring flips to the brighter green.
const ON_INK: readonly Pair[] = [
  {
    label: "body text on dark (paper on ink-deep)",
    foreground: "color-paper",
    ground: "color-ink-deep",
    floor: 4.5,
  },
  {
    label: "secondary text on dark (trace-dark on ink-deep)",
    foreground: "color-trace-dark",
    ground: "color-ink-deep",
    floor: 4.5,
  },
  {
    label: "focus ring and run status on dark (ring on ink-deep)",
    foreground: "ring",
    ground: "color-ink-deep",
    floor: 4.5,
  },
  {
    label: "experience rows (paper at 85 percent on ink-deep)",
    foreground: "color-paper",
    ground: "color-ink-deep",
    floor: 4.5,
    alpha: 0.85,
  },
];

test("every text pair on the paper sheet clears its floor", () => {
  for (const pair of ON_PAPER) measure(PAPER, pair);
});

test("every text pair on the dark bands clears its floor", () => {
  for (const pair of ON_INK) measure(INK, pair);
});

/**
 * The focus indicator is a named token on both grounds, not a literal repeated in a rule. Asserted
 * apart from the pairs above because the failure it guards is a different one: not a colour
 * drifting under a ratio, but --ring being deleted, or losing one of its two scopes, while the two
 * green tokens themselves stay perfectly legal.
 */
test("--ring is defined on both grounds and aliases the green of each", () => {
  atLeast(contrastRatio(hexOf(PAPER, "ring"), hexOf(PAPER, "color-paper")), 3, "--ring on paper");
  atLeast(contrastRatio(hexOf(INK, "ring"), hexOf(INK, "color-ink-deep")), 3, "--ring on ink");
  assert.equal(hexOf(PAPER, "ring"), hexOf(PAPER, "color-stamp"), "--ring on paper is the stamp");
  assert.equal(
    hexOf(INK, "ring"),
    hexOf(INK, "color-stamp-dark"),
    "--ring on dark is the bright green"
  );
});

/**
 * Law 3 of the spec, measured on Attio (#1c1d1f), Ramp (#0c0a08) and Column (navy): the ink of a
 * finance page is never #000, and its ground is never #fff. Pure black on pure white is 21:1, a
 * contrast nobody needs and an edge every one of those sites paid to soften. This site was already
 * built that way; the test is here so it stays that way.
 */
test("the ink is never pure black and the paper never pure white", () => {
  assert.notEqual(hexOf(PAPER, "color-ink"), "#000000", "pure black ink is refused by the spec");
  assert.notEqual(hexOf(INK, "color-ink-deep"), "#000000", "pure black ground is refused");
  assert.notEqual(hexOf(PAPER, "color-paper"), "#ffffff", "pure white paper is refused");
});
